# Generated by Django 4.2.5 on 2023-09-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_person_code_alter_person_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='added_by',
            field=models.CharField(default='guest', max_length=20),
        ),
    ]
